import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"

import { menu } from "@/actions/menu"

import { cn } from "@/lib/utils"
import { Header } from "@/components/header"
import { sectionVariants } from "@/components/section"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const menuQuery = await menu({})
  return (
    <html lang="en">
      <body
        className={cn([
          inter.className,
          // "mt-24",
          // sectionVariants({ spacer: "p", side: "t" }),
        ])}
      >
        <Header nav={menuQuery?.nav} />
        {children}
      </body>
    </html>
  )
}
